# Exercise 1 Cereals Data Set â€“ Data Preprocessing

### Abeer Sethia | 220968144 | Batch B1 | Week 2 | Exercise 1

Using the given CEREALS dataset, perform data preprocessing and answer the following questions.
1) Create a table with the 5-number summary of all the numeric attributes.
2) For each of the numeric attributes (proteins up to vitamins), identify and replace all missing data (indicated with -1) with the arithmetic mean of the attribute.
3) Create a table with the 5-number summary of all the numeric attributes after treating missing values. Do you think the strategy used in dealing with missing values was effective?
4) For each of the numeric attributes (proteins up to vitamins), identify and replace all noisy data with the median of attribute.
5) Create a table with the 5-number summary of all the numeric attributes after treating noisy values. Do you think the strategy used in dealing with noisy values was effective?

### Importing the libraries

In [15]:
import numpy as np
import pandas as pd
from numpy import percentile
from numpy.random import rand

### Importing and printing the dataset

In [16]:
df=pd.read_csv("Cereals.csv")

In [17]:
print(df)

                      name mfr type  calories  protein  fat  sodium  fiber  \
0           100NaturalBran   Q    C       120        3    5      15    2.0
1                 All-Bran   K    C        70        4    1     260    9.0
2   All-BranwithExtraFiber   K    C        50        4    0     140   14.0
3            AlmondDelight   R    C       110        2    2     200    1.0
4    AppleCinnamonCheerios   G    C       110        2    2     180    1.5
..                     ...  ..  ...       ...      ...  ...     ...    ...
71                 Triples   G    C       110        2    1     250    0.0
72                    Trix   G    C       110        1    1     140    0.0
73               WheatChex   R    C       100        3    1     230    3.0
74                Wheaties   G    C       100        3    1     200    3.0
75       WheatiesHoneyGold   G    C       110        2    1     200    1.0

   carbo sugars potass  vitamins  shelf  weight  cups     rating
0      8      8    135         0      3     1.0  1.00  33.983679
1      7      5    320        25      3     1.0  0.33  59.425505
2      8      0    330        25      3     1.0  0.50  93.704912
3     14      8      ?        25      3     1.0  0.75  34.384843
4   10.5     10     70        25      1     1.0  0.75  29.509541
..   ...    ...    ...       ...    ...     ...   ...        ...
71    21      3     60        25      3     1.0  0.75  39.106174
72    13     12     25        25      2     1.0  1.00  27.753301
73    17      3    115        25      1     1.0  0.67  49.787445
74    17      3    110        25      1     1.0  1.00  51.592193
75    16      8     60        25      1     1.0  0.75  36.187559

[76 rows x 16 columns]

### 1. Create a table with the 5-number summary of all the numeric attributes

In [18]:
df.describe()

,calories,protein,fat,sodium,fiber,vitamins,shelf,weight,cups,rating
count,76.000000,76.000000,76.000000,76.000000,76.000000,76.000000,76.000000,76.000000,76.000000,76.000000
mean,107.368421,2.526316,1.013158,160.065789,2.048684,28.289474,2.197368,1.030000,0.827500,42.327057
std,19.139378,1.089020,1.013159,84.318813,2.219038,22.487813,0.832982,0.151438,0.227204,13.820602
min,50.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.500000,0.250000,18.042851
25%,100.000000,2.000000,0.000000,132.500000,0.750000,25.000000,1.000000,1.000000,0.670000,32.932466
50%,110.000000,2.500000,1.000000,180.000000,1.750000,25.000000,2.000000,1.000000,0.750000,40.253086
75%,110.000000,3.000000,2.000000,212.500000,3.000000,25.000000,3.000000,1.000000,1.000000,50.780847
max,160.000000,6.000000,5.000000,320.000000,14.000000,100.000000,3.000000,1.500000,1.500000,93.704912

### 2. For each of the numeric attributes (proteins up to vitamins), identify and replace all missing data (indicated with -1) with the arithmetic mean of the attribute.

In [19]:
cols = ['protein', 'fat', 'sodium', 'fiber', 'carbo', 'sugars', 'potass', 'vitamins']
Q3 = df[cols].quantile(0.75)
Q1 = df[cols].quantile(0.25)
IQR = Q3 - Q1
df[(df[cols] <=Q3+(1.5*IQR)) & (df[cols] >=Q1-(1.5*IQR))]
df.fillna(df.median())
df

/var/folders/bf/7f2sjmd95md4m9hcdf6rwbp40000gn/T/ipykernel_2413/1862665757.py:2: FutureWarning: The default value of numeric_only in DataFrame.quantile is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  Q3 = df[cols].quantile(0.75)
/var/folders/bf/7f2sjmd95md4m9hcdf6rwbp40000gn/T/ipykernel_2413/1862665757.py:3: FutureWarning: The default value of numeric_only in DataFrame.quantile is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  Q1 = df[cols].quantile(0.25)
/var/folders/bf/7f2sjmd95md4m9hcdf6rwbp40000gn/T/ipykernel_2413/1862665757.py:5: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version. Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  df[(df[cols] <=Q3+(1.5*IQR)) & (df[cols] >=Q1-(1.5*IQR))]
/var/folders/bf/7f2sjmd95md4m9hcdf6rwbp40000gn/T/ipykernel_2413/1862665757.py:5: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version. Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  df[(df[cols] <=Q3+(1.5*IQR)) & (df[cols] >=Q1-(1.5*IQR))]
/var/folders/bf/7f2sjmd95md4m9hcdf6rwbp40000gn/T/ipykernel_2413/1862665757.py:6: FutureWarning: The default value of numeric_only in DataFrame.median is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.fillna(df.median())

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
0,100NaturalBran,Q,C,120,3,5,15,2.0,8,8,135,0,3,1.0,1.00,33.983679
1,All-Bran,K,C,70,4,1,260,9.0,7,5,320,25,3,1.0,0.33,59.425505
2,All-BranwithExtraFiber,K,C,50,4,0,140,14.0,8,0,330,25,3,1.0,0.50,93.704912
3,AlmondDelight,R,C,110,2,2,200,1.0,14,8,?,25,3,1.0,0.75,34.384843
4,AppleCinnamonCheerios,G,C,110,2,2,180,1.5,10.5,10,70,25,1,1.0,0.75,29.509541
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71,Triples,G,C,110,2,1,250,0.0,21,3,60,25,3,1.0,0.75,39.106174
72,Trix,G,C,110,1,1,140,0.0,13,12,25,25,2,1.0,1.00,27.753301
73,WheatChex,R,C,100,3,1,230,3.0,17,3,115,25,1,1.0,0.67,49.787445
74,Wheaties,G,C,100,3,1,200,3.0,17,3,110,25,1,1.0,1.00,51.592193
75,WheatiesHoneyGold,G,C,110,2,1,200,1.0,16,8,60,25,1,1.0,0.75,36.187559

### 3. Create a table with the 5-number summary of all the numeric attributes after treating missing values. Do you think the strategy used in dealing with missing values was effective?

#### a) 5 Number summary before treating missing values

In [20]:
df.describe()

,calories,protein,fat,sodium,fiber,vitamins,shelf,weight,cups,rating
count,76.000000,76.000000,76.000000,76.000000,76.000000,76.000000,76.000000,76.000000,76.000000,76.000000
mean,107.368421,2.526316,1.013158,160.065789,2.048684,28.289474,2.197368,1.030000,0.827500,42.327057
std,19.139378,1.089020,1.013159,84.318813,2.219038,22.487813,0.832982,0.151438,0.227204,13.820602
min,50.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.500000,0.250000,18.042851
25%,100.000000,2.000000,0.000000,132.500000,0.750000,25.000000,1.000000,1.000000,0.670000,32.932466
50%,110.000000,2.500000,1.000000,180.000000,1.750000,25.000000,2.000000,1.000000,0.750000,40.253086
75%,110.000000,3.000000,2.000000,212.500000,3.000000,25.000000,3.000000,1.000000,1.000000,50.780847
max,160.000000,6.000000,5.000000,320.000000,14.000000,100.000000,3.000000,1.500000,1.500000,93.704912

#### b) Removing the Outliers

In [21]:
cols = ['protein', 'fat', 'sodium', 'fiber', 'carbo', 'sugars', 'potass', 'vitamins']
Q3 = df[cols].quantile(0.75)
Q1 = df[cols].quantile(0.25)
IQR = Q3 - Q1
df[(df[cols] <=Q3+(1.5*IQR)) & (df[cols] >=Q1-(1.5*IQR))]
df.fillna(df.median())
df

/var/folders/bf/7f2sjmd95md4m9hcdf6rwbp40000gn/T/ipykernel_2413/1862665757.py:2: FutureWarning: The default value of numeric_only in DataFrame.quantile is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  Q3 = df[cols].quantile(0.75)
/var/folders/bf/7f2sjmd95md4m9hcdf6rwbp40000gn/T/ipykernel_2413/1862665757.py:3: FutureWarning: The default value of numeric_only in DataFrame.quantile is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  Q1 = df[cols].quantile(0.25)
/var/folders/bf/7f2sjmd95md4m9hcdf6rwbp40000gn/T/ipykernel_2413/1862665757.py:5: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version. Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  df[(df[cols] <=Q3+(1.5*IQR)) & (df[cols] >=Q1-(1.5*IQR))]
/var/folders/bf/7f2sjmd95md4m9hcdf6rwbp40000gn/T/ipykernel_2413/1862665757.py:5: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version. Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  df[(df[cols] <=Q3+(1.5*IQR)) & (df[cols] >=Q1-(1.5*IQR))]
/var/folders/bf/7f2sjmd95md4m9hcdf6rwbp40000gn/T/ipykernel_2413/1862665757.py:6: FutureWarning: The default value of numeric_only in DataFrame.median is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.fillna(df.median())

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
0,100NaturalBran,Q,C,120,3,5,15,2.0,8,8,135,0,3,1.0,1.00,33.983679
1,All-Bran,K,C,70,4,1,260,9.0,7,5,320,25,3,1.0,0.33,59.425505
2,All-BranwithExtraFiber,K,C,50,4,0,140,14.0,8,0,330,25,3,1.0,0.50,93.704912
3,AlmondDelight,R,C,110,2,2,200,1.0,14,8,?,25,3,1.0,0.75,34.384843
4,AppleCinnamonCheerios,G,C,110,2,2,180,1.5,10.5,10,70,25,1,1.0,0.75,29.509541
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71,Triples,G,C,110,2,1,250,0.0,21,3,60,25,3,1.0,0.75,39.106174
72,Trix,G,C,110,1,1,140,0.0,13,12,25,25,2,1.0,1.00,27.753301
73,WheatChex,R,C,100,3,1,230,3.0,17,3,115,25,1,1.0,0.67,49.787445
74,Wheaties,G,C,100,3,1,200,3.0,17,3,110,25,1,1.0,1.00,51.592193
75,WheatiesHoneyGold,G,C,110,2,1,200,1.0,16,8,60,25,1,1.0,0.75,36.187559

#### c) 5 Number Summary after treating the outliers

In [22]:
df.describe()

,calories,protein,fat,sodium,fiber,vitamins,shelf,weight,cups,rating
count,76.000000,76.000000,76.000000,76.000000,76.000000,76.000000,76.000000,76.000000,76.000000,76.000000
mean,107.368421,2.526316,1.013158,160.065789,2.048684,28.289474,2.197368,1.030000,0.827500,42.327057
std,19.139378,1.089020,1.013159,84.318813,2.219038,22.487813,0.832982,0.151438,0.227204,13.820602
min,50.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.500000,0.250000,18.042851
25%,100.000000,2.000000,0.000000,132.500000,0.750000,25.000000,1.000000,1.000000,0.670000,32.932466
50%,110.000000,2.500000,1.000000,180.000000,1.750000,25.000000,2.000000,1.000000,0.750000,40.253086
75%,110.000000,3.000000,2.000000,212.500000,3.000000,25.000000,3.000000,1.000000,1.000000,50.780847
max,160.000000,6.000000,5.000000,320.000000,14.000000,100.000000,3.000000,1.500000,1.500000,93.704912

***Strategy used to deal with missing values is effective.***

### 4. For each of the numeric attributes (proteins up to vitamins), identify and replace all noisy data with the median of attribute.

In [23]:
cols = ['protein', 'fat', 'sodium', 'fiber', 'carbo', 'sugars', 'potass', 'vitamins']
Q3 = df[cols].quantile(0.75)
Q1 = df[cols].quantile(0.25)
IQR = Q3 - Q1
df[(df[cols] <=Q3+(1.5*IQR)) & (df[cols] >=Q1-(1.5*IQR))]
df.fillna(df.median())
df

/var/folders/bf/7f2sjmd95md4m9hcdf6rwbp40000gn/T/ipykernel_2413/1862665757.py:2: FutureWarning: The default value of numeric_only in DataFrame.quantile is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  Q3 = df[cols].quantile(0.75)
/var/folders/bf/7f2sjmd95md4m9hcdf6rwbp40000gn/T/ipykernel_2413/1862665757.py:3: FutureWarning: The default value of numeric_only in DataFrame.quantile is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  Q1 = df[cols].quantile(0.25)
/var/folders/bf/7f2sjmd95md4m9hcdf6rwbp40000gn/T/ipykernel_2413/1862665757.py:5: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version. Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  df[(df[cols] <=Q3+(1.5*IQR)) & (df[cols] >=Q1-(1.5*IQR))]
/var/folders/bf/7f2sjmd95md4m9hcdf6rwbp40000gn/T/ipykernel_2413/1862665757.py:5: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version. Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  df[(df[cols] <=Q3+(1.5*IQR)) & (df[cols] >=Q1-(1.5*IQR))]
/var/folders/bf/7f2sjmd95md4m9hcdf6rwbp40000gn/T/ipykernel_2413/1862665757.py:6: FutureWarning: The default value of numeric_only in DataFrame.median is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.fillna(df.median())

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
0,100NaturalBran,Q,C,120,3,5,15,2.0,8,8,135,0,3,1.0,1.00,33.983679
1,All-Bran,K,C,70,4,1,260,9.0,7,5,320,25,3,1.0,0.33,59.425505
2,All-BranwithExtraFiber,K,C,50,4,0,140,14.0,8,0,330,25,3,1.0,0.50,93.704912
3,AlmondDelight,R,C,110,2,2,200,1.0,14,8,?,25,3,1.0,0.75,34.384843
4,AppleCinnamonCheerios,G,C,110,2,2,180,1.5,10.5,10,70,25,1,1.0,0.75,29.509541
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71,Triples,G,C,110,2,1,250,0.0,21,3,60,25,3,1.0,0.75,39.106174
72,Trix,G,C,110,1,1,140,0.0,13,12,25,25,2,1.0,1.00,27.753301
73,WheatChex,R,C,100,3,1,230,3.0,17,3,115,25,1,1.0,0.67,49.787445
74,Wheaties,G,C,100,3,1,200,3.0,17,3,110,25,1,1.0,1.00,51.592193
75,WheatiesHoneyGold,G,C,110,2,1,200,1.0,16,8,60,25,1,1.0,0.75,36.187559

### 5) Create a table with the 5-number summary of all the numeric attributes after treating noisy values. Do you think the strategy used in dealing with noisy values was effective?

In [24]:
df.describe()

,calories,protein,fat,sodium,fiber,vitamins,shelf,weight,cups,rating
count,76.000000,76.000000,76.000000,76.000000,76.000000,76.000000,76.000000,76.000000,76.000000,76.000000
mean,107.368421,2.526316,1.013158,160.065789,2.048684,28.289474,2.197368,1.030000,0.827500,42.327057
std,19.139378,1.089020,1.013159,84.318813,2.219038,22.487813,0.832982,0.151438,0.227204,13.820602
min,50.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.500000,0.250000,18.042851
25%,100.000000,2.000000,0.000000,132.500000,0.750000,25.000000,1.000000,1.000000,0.670000,32.932466
50%,110.000000,2.500000,1.000000,180.000000,1.750000,25.000000,2.000000,1.000000,0.750000,40.253086
75%,110.000000,3.000000,2.000000,212.500000,3.000000,25.000000,3.000000,1.000000,1.000000,50.780847
max,160.000000,6.000000,5.000000,320.000000,14.000000,100.000000,3.000000,1.500000,1.500000,93.704912

***Strategy used to deal with noisy data is effective.***